### ISSUE TITLE
Refactor each parser method to no more than 40 rows

### ISSUE THREAD

**Issue by pavlo-k-kostenko** [PavelKostenko/ForecastAdviser#18]

**Comment by Demishev** [comment]
No, it's not.
Do not see it in the repository.

On Tue, May 19, 2015 at 9:51 PM, PavelKostenko notifications@github.com
wrote:

> Closed #18 https://github.com/PavelKostenko/ForecastAdviser/issues/18.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PavelKostenko/ForecastAdviser/issues/18#event-308794977
> .

## 

Thanks,
Konstantin Demishev
+38(050)471-63-67

**Comment by Demishev** [comment]
And now it is :) Good job.
