### ISSUE TITLE
Clean deployment from GitHub after converting the project to Maven

### ISSUE THREAD

**Issue by pavlo-k-kostenko** [PavelKostenko/ForecastAdviser#38]
Please check:
Was you able to clone and build the project without any problems?
Are there any dependencies forgotten?
Are there any missing or excess files in the project on GitHub?

**Comment by Demishev** [comment]
To check it manually you can:
1. Create some new folder.
2. Open it with cmd.
3. Clone your project to this folder (git clone .... )
4. Enter to root folder of your project and type mvn clean install.
5. Verify BUILD SUCCESS message.

**Comment by Demishev** [comment]
To do this in some automated way you can connect project to some CI tool.
For this open project you can use Travis CI. It is free, cloud based and easy to use.

**Comment by Demishev** [comment]
Also I was unable to compile this project because I do not have 1.7 java: only 1.6 and 1.8.

**Comment by pavlo-k-kostenko** [comment]
I changed the version to 1.8. Can you try to compile until I implement Travis? =)

**Comment by Demishev** [comment]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.660s
[INFO] Finished at: Tue May 19 11:01:52 EEST 2015
[INFO] Final Memory: 20M/223M
[INFO] ------------------------------------------------------------------------

**Comment by Demishev** [comment]
wtf do you want of me about this issue?

**Comment by pavlo-k-kostenko** [comment]
I didn't touch the issue since you tested :) The issue is closed now
